MAJOR -> CODE OF CONDUCT A APROBAR
Soft-Coders/ABD pull request #27
Opened 2022-03-28 17:18 UTC by jesuscestino

2022-03-28 18:57 UTC, ghost requested changes
- Hay faltas de ortografía (tildes). 
- El indice estaría bien que tuviese un shortcut para ir al apartado correspondiente

2022-03-28 19:27 UTC, iLopezosa requested changes
Las listas numeradas no deben de ir precedidas por "-". 
Y sustituiría:
- Preambulo

por

> Preambulo

2022-03-28 20:25 UTC, martame18 commented
En el índice enlazaría los títulos correspondientes o lo eliminaría por ser un documento pequeño.

2022-03-29 07:33 UTC, iLopezosa approved these changes
A parte de eso OK

2022-03-29 07:33 UTC, iLopezosa commented on CODE_OF_CONDUCT.md
> +Preámbulo: Los integrantes de este grupo se comprometen a cumplir la normativa estipulada en este documento.
> Preámbulo

2022-03-29 07:34 UTC, jesuscestino commented on CODE_OF_CONDUCT.md
> +Preámbulo: Los integrantes de este grupo se comprometen a cumplir la normativa estipulada en este documento.
OK

2022-03-29 07:59 UTC, pablohud commented on CODE_OF_CONDUCT.md
> +## INDICE
ÍNDICE*

2022-03-29 07:59 UTC, pablohud commented on CODE_OF_CONDUCT.md
> +6. Si en algún momento algún integrante del grupo o varios no se sienten en disposición de continuar la reunión, se deberá comunicar al grupo y solventar la situación lo antes posible de acuerdo a lo
"algún" repetido en poco tiempo*

2022-03-29 07:59 UTC, pablohud commented on CODE_OF_CONDUCT.md
> +1. Los documentos solicitados antes de un comeet serán entregados en el periodo de tiempo estipulado.
Comeet* (con mayúsculas)

2022-03-29 08:35 UTC, ghost approved these changes
OK, me comprometo a cumplirlos

2022-03-29 19:22 UTC, merged